a.out: src/main.rs src/ai.rs
	cargo build --release
	cp ./target/release/ai a.out
dev: src/main.rs src/ai.rs
	cargo build
main.cpp:
	cp ../../common/hasi_template2/main.cpp ./
common.hpp:
	cp ../../common/hasi_template2/common.hpp ./
