a.out: main.cpp ai.hpp ai_base.hpp common.hpp
	g++ -std=c++14 -O2 main.cpp -o a.out
main.cpp:
	cp ../../common/hasi_template2/main.cpp ./
common.hpp:
	cp ../../common/hasi_template2/common.hpp ./
ai_base.hpp:
	:
